=== Pawe1/log4d/src/log4d.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Author: Keith Wood. -->

<!-- A configuration element consists of optional renderer elements,
     appender elements, categories, and an optional root element. -->

<!ELEMENT log4d:configuration (renderer*, appender*, category*, root?)>


<!-- The categoryFactory attribute names the factory to be used to
     create new instances of categories.

     Setting the debug attribute enable the printing
     of internal log4d logging statements.
     By default, the debug attribute is "null", meaning
     that we not touch internal log4d logging settings.

     The disable attribute takes a priority value such that all logging
     statements with a priority equal or below this value are disabled.

     The disableOverride attribute allows the user to override any
     BasicConfigurator.disable invocations made from within the application.

     By default, disableOverride is "null", meaning that we
     do not touch the disable flag. -->

<!ATTLIST log4d:configuration
  categoryFactory CDATA #IMPLIED
  debug           (true | false | null) "null"
  disable         CDATA "null"
  disableOverride (true | false | null) "null"
>

<!-- Renderer elements allow the user to customize the conversion of
     message objects to strings. -->

<!ELEMENT renderer EMPTY>
<!ATTLIST renderer
  renderedClass  CDATA #REQUIRED
  renderingClass CDATA #REQUIRED
>

<!-- Appenders must have a name and a class. Appenders may contain
     an error handler, parameters, a layout, and filters. -->

<!ELEMENT appender (errorHandler?, param*, layout?, filter*)>
<!ATTLIST appender
  name  ID    #REQUIRED
  class CDATA #REQUIRED
>

<!-- ErrorHandlers can be of any class.
     They can admit any number of parameters. -->

<!ELEMENT errorHandler (param*)>
<!ATTLIST errorHandler
  class CDATA #REQUIRED
>

<!-- Layouts can be of any class.
     They can admit any number of parameters. -->

<!ELEMENT layout (param*)>
<!ATTLIST layout
  class CDATA #REQUIRED
>

<!-- Filters can be of any class.
     They can admit any number of parameters. -->

<!ELEMENT filter (param*)>
<!ATTLIST filter
  class CDATA #REQUIRED
>

<!-- Parameters have a name and a value. -->

<!ELEMENT param EMPTY>
<!ATTLIST param
  name  CDATA #REQUIRED
  value CDATA #REQUIRED
>

<!-- Priorities are identified by name. -->

<!ELEMENT priority EMPTY>
<!ATTLIST priority
  name CDATA #REQUIRED
>

<!-- If no priority element is specified, then the configurator
     MUST not touch the priority of the named category. -->

<!ELEMENT category (param*, priority?, appender-ref*)>
<!ATTLIST category
  class    CDATA #IMPLIED
  name     CDATA #REQUIRED
  additive (true | false) "true"
>

<!-- If no priority element is specified, then the configurator
     MUST not touch the priority of root.
     The root category always exists and cannot be subclassed. -->

<!ELEMENT root (param*, priority?, appender-ref*)>

<!-- Refer back to the appender defined earlier. -->

<!ELEMENT appender-ref EMPTY>
<!ATTLIST appender-ref
  ref IDREF #REQUIRED
>

<!-- ==================================================================== -->
<!-- The following definitions are for use
     in formatting logging events as XML. -->

<!ELEMENT log4d:eventSet (log4d:event*)>

<!ELEMENT log4d:event (log4d:message, log4d:NDC?, log4d:exception?) >

<!-- The timestamp format is application dependent. -->

<!ATTLIST log4d:event
  category  CDATA #REQUIRED
  priority  CDATA #REQUIRED
  thread    CDATA #REQUIRED
  timestamp CDATA #REQUIRED
>

<!ELEMENT log4d:message (#PCDATA)>

<!ELEMENT log4d:NDC (#PCDATA)>

<!ELEMENT log4d:exception (#PCDATA)>

=== Pawe1/log4d/chainsaw/out.xml
<?xml version="1.0"?>
<!DOCTYPE log4d:eventSet SYSTEM "log4d.dtd">
<log4d:eventSet version="1.2" xmlns:log4d="http://log4d.sourceforge.net/log4d">

<log4d:event logger="alt" levelName="FATAL" levelValue="50000" thread="1772" timestamp="20030924222937763" elapsed="23443"><log4d:message><![CDATA[adasdas]]></log4d:message></log4d:event>

<log4d:event logger="alt" levelName="ERROR" levelValue="40000" thread="1772" timestamp="20030924222939776" elapsed="25456"><log4d:message><![CDATA[adasdas]]></log4d:message></log4d:event>

<log4d:event logger="alt" levelName="WARN" levelValue="30000" thread="1772" timestamp="20030924222941899" elapsed="27579"><log4d:message><![CDATA[adasdas]]></log4d:message></log4d:event>

<log4d:event logger="alt" levelName="INFO" levelValue="20000" thread="1772" timestamp="20030924222947608" elapsed="33288"><log4d:message><![CDATA[adasdas]]></log4d:message></log4d:event>

</log4d:eventSet>

=== Pawe1/log4d/demo/log4d.xml
<?xml version="1.0"?>
<!DOCTYPE log4d:configuration SYSTEM "log4d.dtd">
<!-- Sample Log4D configuration file as an XML document. -->
<log4d:configuration xmlns:log4d="urn:log4d"
  categoryFactory="TLogDefaultCategoryFactory" debug="true"
  disable="info"> <!-- disableOverride="true" -->

  <!-- Associate object renderers with objects. -->
  <renderer renderedClass="TComponent" renderingClass="TComponentRenderer"/>

  <!-- Define appenders, with layouts and optional parameters. -->
  <appender name="ODS" class="TLogODSAppender">
    <layout class="TLogSimpleLayout"/>
  </appender>

  <appender name="Mem1" class="TMemoAppender">
    <layout class="TLogPatternLayout">
      <param name="pattern" value="%7r [%-8t] %p %c %x - %m%n"/>
    </layout>
    <param name="memo" value="memMyapp"/>
    <filter class="TLogStringFilter">
      <param name="match" value="x"/>
      <param name="acceptOnMatch" value="true"/>
    </filter>
    <filter class="TLogStringFilter">
      <param name="match" value="y"/>
      <param name="acceptOnMatch" value="false"/>
    </filter>
  </appender>

  <appender name="Mem2" class="TMemoAppender">
    <layout class="TLogSimpleLayout"/>
    <param name="memo" value="memMyappMore"/>
  </appender>

  <appender name="Mem3" class="TMemoAppender">
    <layout class="TLogHTMLLayout"/>
    <param name="memo" value="memMyappOther"/>
  </appender>

  <appender name="Mem4" class="TMemoAppender">
    <layout class="TLogXMLLayout"/>
    <param name="memo" value="memAlt"/>
  </appender>

  <appender name="Fil1" class="TLogFileAppender">
    <param name="filename" value="C:\Temp\Log4D.log"/>
    <layout class="TLogPatternLayout">
      <param name="pattern" value="%r [%t] %p %c %x - %m%n"/>
    </layout>
  </appender>

  <!--appender name="Email" class="TLogNMSMTPAppender">
    <param name="bufferSize" value="10"/>
    <param name="from" value="Log4D &lt;log4d@log4d.com&gt;"/>
    <param name="host" value="mail.log4d.com"/>
    <param name="subject" value="Log4D Demonstration"/>
    <param name="to" value="Administrator &lt;admin@log4d.com&gt;"/>
    <layout class="TLogPatternLayout">
      <param name="pattern" value="%r [%t] %p %c %x - %m%n"/>
    </layout>
  </appender-->

  <!-- Define categories and their priorities and appenders. -->
  <category name="myapp">
    <priority value="inherited"/>
    <appender-ref ref="Mem1"/>
  </category>
  <category name="myapp.more">
    <priority value="debug"/>
    <appender-ref ref="Mem2"/>
  </category>
  <category name="myapp.other" additive="false">
    <priority value="info"/>
    <appender-ref ref="Mem3"/>
    <!--appender-ref ref="Email"/-->
  </category>
  <category name="alt">
    <priority value="error"/>
    <appender-ref ref="Mem4"/>
    <appender-ref ref="Fil1"/>
  </category>

  <!-- Establish the root category's properties. -->
  <root>
    <priority value="warn"/>
    <appender-ref ref="ODS"/>
  </root>
</log4d:configuration>
